In [ ]:
import pandas as pd
import seaborn as sns
import requests
from tqdm import tqdm
import numpy as np
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
import sys

sys.path.append(str(Path("..").resolve()))
from src import *
sns.set_style("darkgrid")
sns.set_context("notebook", font_scale=1.15)
tqdm.pandas()

# Check the availability of the thumbnails
##### ℹ️ This notebook requires `dataset/objaverse/1-annotations_filtered.parquet` and outputs `dataset/objaverse/2-annotations_filtered_by_thumbnails.parquet`
This notebook processes the thumbnails according to their current availability (HTTP 200) and selects the version with the highest resolution.

In [14]:
annotations = pd.read_parquet('../dataset/objaverse/1-annotations_filtered.parquet')
annotations.head(1)

,name,likeCount,animationCount,commentCount,tags,categories,thumbnails,description,faceCount,createdAt,vertexCount,archives
uid,,,,,,,,,,,,
e030179d25844f4c897c2a653edfe784,Bizcochuelo,0,0,0,[],[],[https://media.sketchfab.com/models/e030179d25...,,12,2020-07-11T22:14:31.150153,8,"{'extra': None, 'glb': {'faceCount': 12, 'size..."

## Using ThreadPoolExecutor to speed up (from 2h:15m to 3m)
Here we select the first higher resolution thumbnail for each object, or None if no thumbnail is available.

In [3]:
MIN_SIZE = 20_000  # bytes


def check_thumbnails(row) -> str | None:
    def get_size(url) -> int:
        try:
            response = requests.head(url, timeout=5)
            if response.status_code == 200 and "Content-Length" in response.headers:
                return int(response.headers["Content-Length"])
            return 0
        except requests.RequestException:
            return None

    if not isinstance(row["thumbnails"], np.ndarray):
        return None

    for thumbnail in row["thumbnails"][::-1] if "x" in row["thumbnails"][0][-8] else row["thumbnails"]:
        if (size := get_size(thumbnail)) is not None and size > MIN_SIZE:
            return thumbnail
    return None

In [4]:
def parallel_apply(df, func, max_workers=8):
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        rows = [row for _, row in df.iterrows()]
        results = list(tqdm(executor.map(func, rows), total=len(rows), desc='Processing'))
    return results

In [5]:
thumbnails = parallel_apply(annotations, check_thumbnails, max_workers=64)

Processing: 100%|██████████| 17921/17921 [01:08<00:00, 263.21it/s]

In [15]:
annotations['thumbnail'] = thumbnails
annotations.drop(columns=['thumbnails'], inplace=True)

In [17]:
annotations_filtered = annotations[annotations["thumbnail"].notna()]
# annotations_filtered.set_index("uid", inplace=True)
annotations_filtered.to_parquet("../dataset/objaverse/thumbnails_checked2.parquet", index=True)

In [22]:
annotations_filtered.to_parquet("../dataset/objaverse/2-annotations_filtered_by_thumbnails.parquet", index=True)

In [19]:
pd.read_parquet('../dataset/objaverse/thumbnails_checked2.parquet')

,name,likeCount,animationCount,commentCount,tags,categories,description,faceCount,createdAt,vertexCount,archives,thumbnail
uid,,,,,,,,,,,,
2dd06635592e4a40bd09b9921cb73754,Jonescrate,0,0,0,[],[],Box,12,2022-03-21T22:56:54.051163,8,"{'extra': None, 'glb': {'faceCount': 12, 'size...",https://media.sketchfab.com/models/2dd06635592...
8a52183eeca8495389c15365fd76951c,object2,0,0,0,[],[],,12,2021-04-02T12:06:23.665083,8,"{'extra': None, 'glb': {'faceCount': 12, 'size...",https://media.sketchfab.com/models/8a52183eeca...
b5f3dbc012ce4351b5462bf0437836f7,Kellen Breccia Bianco,0,0,0,"[sample, kellen, bianco, paving, breccia, hard...",[architecture],Kellen Breccia Bianco paving sample,24,2020-05-20T10:48:31.835140,8,"{'extra': None, 'glb': {'faceCount': 24, 'size...",https://media.sketchfab.com/models/b5f3dbc012c...
9b367fed57aa46bc9d2414ad8d88f07d,Pieza 2,0,0,0,[],[],,40,2021-11-15T09:50:08.927970,22,"{'extra': None, 'glb': {'faceCount': 40, 'size...",https://media.sketchfab.com/models/9b367fed57a...
7f05713c5f6144d8b6ba9a3e2464197d,Copo,0,0,0,[],[furniture-home],ALUNO: Arthur Santos Leandro\nDISCIPLINA: Mode...,56,2018-06-11T13:14:05.149160,33,"{'extra': None, 'glb': {'faceCount': 56, 'size...",https://media.sketchfab.com/models/7f05713c5f6...
...,...,...,...,...,...,...,...,...,...,...,...,...
c4c83906fda64cf5bdba463accf976d2,CUBE TIKRA,0,0,0,[],[],,12,2021-06-09T15:46:41.483577,8,"{'extra': None, 'glb': {'faceCount': 12, 'size...",https://media.sketchfab.com/models/c4c83906fda...
075086c5324f46c49ea8cffae46c251d,Kellen Lavaro Zwart 509,1,0,0,"[sample, kellen, 509, paving, hardscape, zwart...",[architecture],Kellen Lavaro Zwart 509 paving sample,24,2020-06-03T12:44:38.398397,8,"{'extra': None, 'glb': {'faceCount': 24, 'size...",https://media.sketchfab.com/models/075086c5324...
ae4e9289a15a4cc19a7331ec20e4f528,Sculpture-jing,0,0,0,[minecraft],[art-abstract],My modle for Assignment1.,52,2020-01-20T23:03:09.899209,28,"{'extra': None, 'glb': {'faceCount': 52, 'size...",https://media.sketchfab.com/models/ae4e9289a15...
0daf4b99b31a4758bd0529908a75b7c8,scene_pouli,0,0,0,[],[],,13,2021-08-11T15:17:00.846299,15,"{'extra': None, 'glb': {'faceCount': 13, 'size...",https://media.sketchfab.com/models/0daf4b99b31...
8f608958704949b7bb7358a1793b54c6,CHAIR,0,0,0,[],[],,86,2019-10-30T01:59:13.133019,60,"{'extra': None, 'glb': {'faceCount': 86, 'size...",https://media.sketchfab.com/models/8f608958704...

## Check for corrupted downloaded thumbnails

In [ ]:
from PIL import Image

corrupted = []
for file in tqdm((ObjaverseDataset3D.DATASET_DIR / "render").glob("*")):
    try:
        Image.open(file)
    except:
        corrupted.append(file)

In [ ]:
cprint("You have", len(corrupted), "corrupted images")

You have 4 corrupted images